version: "3.9"

services:
  web:
    build: .
    container_name: pitch_api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    build: .
    container_name: pitch_worker
    command: celery -A app.pitchtasks worker --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:6.2
    container_name: redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "6379:6379"