version: "3.8"

services:
  resume-parser-llm:
    build: .
    ports:
      - "8005:8000"
    environment:
      OPENAI_API_KEY: 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
      ANTHROPIC_API_KEY: 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
      LOCAL_LLM_URL: ${LOCAL_LLM_URL}
      POSTGRES_URL: postgresql://user:password@postgres:5432/resumedb
      MINIO_URL: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: resumes
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
    # depends_on:
    #   qdrant:
    #     condition: service_healthy
    #   postgres:
    #     condition: service_started
    #   minio:
    #     condition: service_started

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: resumedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6334:6333"
    volumes:
      - qdrantdata:/qdrant/storage
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  qdrantdata:
  miniodata:
