version: "3.9"

services:
  redis:
    image: redis:6.2
    container_name: shared_redis
    ports:
      - "6379:6379"

  flask_web:
    build:
      context: ./magure_ai_resume
    container_name: flask_web
    command: python run.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    ports:
      - "5001:5001"
    depends_on:
      - redis
    volumes:
      - ./magure_ai_resume:/app

  flask_celery:
    build:
      context: ./magure_ai_resume
    container_name: flask_celery
    command: celery -A celery_worker worker  -Q resume_tasks --pool=threads --concurrency=8 --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - redis
    volumes:
      - ./magure_ai_resume:/app

  fastapi_web:
    build:
      context: ./pitch-analyzer
    container_name: fastapi_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./pitch-analyzer:/app

  fastapi_celery:
    build:
      context: ./pitch-analyzer
    container_name: fastapi_celery
    command: celery -A app.pitchtasks worker -Q pitch_tasks  --pool=threads --concurrency=4 --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./pitch-analyzer:/app

  # ───── Chatbox Backend (FastAPI) ─────
  # ───── PostgreSQL for Chatbox ─────
  chatbox_postgres:
    image: postgres:13
    container_name: chatbox_postgres
    environment:
      POSTGRES_DB: chatbox_db
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
    volumes:
      - chatbox_pg_data:/var/lib/postgresql/data
   # ports:
    #  - "5433:5432"  # Optional external port

  # ───── Chatbox FastAPI App ─────
  chatbox_backend:
    build:
      context: ./MagureAi-Chat-Box/chatbox-backend
    container_name: chatbox_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      PGHOST: chatbox_postgres
      PGDATABASE: chatbox_db
      PGUSER: chatuser
      PGPASSWORD: chatpass
    depends_on:
      - chatbox_postgres
    ports:
      - "8001:8001"
    volumes:
      - ./MagureAi-Chat-Box/chatbox-backend:/app


  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
  chatbox_pg_data:
