version: "3.8"

services:
  resume-parser:
    build: .
    ports:
      - "8001:8000"
    environment:
      OPENAI_API_KEY: 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
      POSTGRES_URL: postgresql://user:password@postgres:5432/resumedb
    depends_on:
      - postgres
      - qdrant

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: resumedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:

